Repository coding-heads/JSM-Pastebin, pull requests merged in 2022-11, with the labels that each got.

#3 Create docs directory with contribution guidelines. Add MIT license.
  LICENSE
  docs/ContributionGuidelines.md
Labels: documentation

#13 Added automated security check
  .github/workflows/codeql.yml
Labels: type: enhancement

#17 Readme 2
  README.md
Labels: type: documentation
